---
title: "Basic Data Analysis Course on Stata"
author: "Md Monowar Hossain"
date: "January 04, 2025"
output:
  beamer_presentation:
    theme: AnnArbor
    colortheme: dolphin
    fonttheme: structurebold
  slidy_presentation: default
subtitle: Summarization of data in Stata
institute: "Institute of Statistical Research and Training (ISRT)  \nUniversity of
  Dhaka  \n\\texttt{mmhossain1@isrt.ac.bd}\n"
---

# Graphical presentation of quantitative data

- A quantitative variable can be presented using different graphs among which histogram and boxplot are very popular.
- The former requires construction of frequency table and the later does not.
- A histogram looks like bar diagram, but it differs by the fact that rectangles touch one another and can be of different widths.
- However, in case of histogram, bar height can represent either the frequency or density.

---


# Histogram

```stata
hist bwt, frequency ///
title("Histogram for birth weight") ///
subtitle("(in gram)") ///
xtitle("Birth weight") ///
ytitle("Frequency")
```


---

# Histogram

```stata
hist bwt, fraction

hist bwt, bin(8) fraction normal

hist bwt, width(1000) fraction normal

hist bwt, width(1000) start(500) fraction normal
```


---

# Boxplot

```stata
graph box bwt

graph hbox bwt

graph box bwt, over(smoke)

```

---

# Scatter plot

```stata
twoway scatter bwt age
```


---


# Line diagram

- Line diagrams are used to track changes over different periods of time.
- For example, assume that on day one of trading, a given stock’s price was $30, resulting in a data point at (1, $30). On day two of trading, the stock’s price was $35, resulting in a data point at (2, $35).
- Each data point can be plotted and connected by a line that visually would show the changes in the values over time.
- If the value of the stock increased daily, the line would slope upward. Conversely, if the price of the stock was steadily decreasing, then the line would slope downward.

---

# Line diagram

```stata
use https://www.stata-press.com/data/r17/uslifeexp
/*(U.S. life expectancy, 1900-1999)*/
line le year
line le le_male le_female year
```


---
